In [5]:
### **MA5204: Aprendizaje de Máquinas**

**Departamento de Ingeniería Matemática, Universidad de Chile**

**Profesor:** Felipe Tobar

**Ayudantes:** Alejandro Cuevas, Mauricio Araneda, Mauricio Romero

SyntaxError: invalid syntax (<ipython-input-5-4e81eb412d62>, line 3)

In [6]:
# importar módulos
import numpy as np

In [8]:
data = np.genfromtxt("T1_Housing.csv",
                     delimiter=',',
                     skip_header=1)
print(data)

[[0.00000000e+00 8.14421498e+04 1.47929557e+06 0.00000000e+00]
 [1.00000000e+00 6.64045968e+04 1.16884582e+06 0.00000000e+00]
 [2.00000000e+00 9.09751133e+04 1.54437975e+06 1.00000000e+00]
 [3.00000000e+00 5.42262913e+04 8.14240282e+05 0.00000000e+00]
 [4.00000000e+00 6.99001340e+04 1.59963447e+06 1.00000000e+00]
 [5.00000000e+00 7.74597579e+04 9.45252192e+05 0.00000000e+00]
 [6.00000000e+00 5.45354537e+04 7.32733236e+05 1.00000000e+00]
 [7.00000000e+00 6.12007262e+04 8.94251069e+05 0.00000000e+00]
 [8.00000000e+00 6.41608159e+04 9.85749787e+05 1.00000000e+00]
 [9.00000000e+00 6.87282271e+04 1.78608575e+06 0.00000000e+00]
 [1.00000000e+01 6.33808147e+04 9.32979361e+05 1.00000000e+00]
 [1.10000000e+01 7.59548183e+04 1.05725258e+06 1.00000000e+00]
 [1.20000000e+01 6.44021282e+04 1.03114675e+06 1.00000000e+00]
 [1.30000000e+01 7.62753326e+04 1.46492916e+06 1.00000000e+00]
 [1.40000000e+01 5.88742738e+04 8.49566086e+05 0.00000000e+00]
 [1.50000000e+01 4.38002920e+04 8.09486710e+05 0.000000